server:
  port: 8085

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.paymentledger.events"

kafka:
  topics:
    expense-created: expense.created
    expense-updated: expense.updated
    expense-deleted: expense.deleted

logging:
  level:
    com.paymentledger: INFO
